version: '3'
services:
    db:
      image: 'mongo'
      ports:
        - '27017:27017'
      volumes:
        - /data/db1:/data/db
    app:
      image: 'coretest:latest'
      ports:
        - '8080-8085:8080'
      restart: 'on-failure'
      depends_on:
        - db
      links:
        - db
    frontend:
      image: 'corefront:latest'
      ports:
        - '3000-3005:3000'
      restart: 'on-failure'
      command: 'npm start'
      links: 
        - app
         

