version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.831.0
    - 2.834.0
    - 2.839.0
    - 2.843.0
    - 2.848.0
    - 2.853.0
    - 2.858.0
    - 2.863.0
    - 2.868.0
    - 2.874.0
    - 2.879.0
    - 2.884.0
  - dependency-name: googleapis
    versions:
    - 67.0.0
    - 67.1.0
    - 67.1.1
    - 68.0.0
    - 70.0.0
    - 71.0.0
  - dependency-name: react-datepicker
    versions:
    - 3.6.0
    - 3.7.0
  - dependency-name: "@babel/register"
    versions:
    - 7.13.14
    - 7.13.8
  - dependency-name: "@tinymce/tinymce-react"
    versions:
    - 3.10.1
    - 3.10.2
    - 3.10.3
    - 3.10.4
    - 3.12.0
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: filepond-plugin-image-preview
    versions:
    - 4.6.5
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: pdf-lib
    versions:
    - 1.15.0
    - 1.16.0
  - dependency-name: darkreader
    versions:
    - 4.9.27
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: "@fortawesome/react-fontawesome"
    versions:
    - 0.1.14
