version: '3.8'
services:
  db:
    restart: always
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    command: 'mongod'
  sce-peripheral-api:
    container_name: sce-peripheral-api
    build:
      context: ./api
      dockerfile: ./peripheral_api/Dockerfile.dev
    ports:
      - '8081:8081'
    restart: 'on-failure'
    stdin_open: true
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./api/package.json:/app/package.json
      - ./api/peripheral_api:/app/peripheral_api
      - ./api/node_modules:/app/node_modules
  sce-cloud-api:
    container_name: sce-cloud-api
    image: cloudapi:latest
    build:
      context: ./api
      dockerfile: ./cloud_api/Dockerfile.dev
    ports:
        - '8082:8082'
    restart: 'on-failure'
    stdin_open: true
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./api/package.json:/app/package.json
      - ./api/cloud_api:/app/cloud_api
      - ./api/node_modules:/app/node_modules

  mainendpoints:
    container_name: mainendpoints
    image: mainendpoints:latest
    build:
      context: ./api
      dockerfile: ./main_endpoints/Dockerfile.dev
    ports:
      - '8080:8080'
    restart: 'on-failure'
    stdin_open: true
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./api/package.json:/app/package.json
      - ./api/main_endpoints:/app/main_endpoints
      - ./api/node_modules:/app/node_modules

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - '3000:3000'
    restart: 'on-failure'
    stdin_open: true
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./package.json:/frontend/package.json
      - ./src:/frontend/src/
      - ./util:/frontend/util/
      - ./public:/frontend/public/
      - ./node_modules:/frontend/node_modules
  
  web:
    image: 'nginx'
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
    restart: 'on-failure'
    depends_on:
      - frontend

volumes:
  mongodb_data:
