http {
    # Run nginx with "npm run start-production"
    # Stop nginx with "npm run stop-production"
    # Reload nginx without stopping server "npm reload-production"

    #logging
    access_log  /var/log/nginx/sce.access.log;

    proxy_cache_path /var/cache/nginx/status levels=1:2 keys_zone=status_cache:10m max_size=10m inactive=60m;
    proxy_temp_path /var/cache/nginx/temp;

    # when we run docker-compose up for the first time, a default
    # network is created that all the containers are attached to.
    # this default network name is the directory name + "_default".
    # As a result, the network name will be "clark_default".
    # To establish a connection to the containers, we can do
    # <container name>.<network name>, and that's what happens below.
    upstream webserver {
        server sce-frontend:3000;
    }
    upstream mainendpoints {
        server sce-main-endpoints:8080;
    }

    server {
        #re-routing http to https server
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
        return 301 https://$host$request_uri;
    }

    # actual nginx server
    server {

        #443(https)
        listen 443 ssl;

        # ssl certificate
        ssl_certificate sce_sjsu_edu_cert.cer;
        ssl_certificate_key sce.key;
        # TLS protocol (remember to update to the newest protocols for best security)
        ssl_protocols TLSv1.2 TLSv1.3;

        location ~ /s/(.*)$ {
            proxy_set_header X-Original-URL "$scheme://$host$request_uri";
            proxy_set_header X-Base-URL "$scheme://$host";
            proxy_pass http://cleezy-nginx.sce;
        }

        location ~ /qr/(.*)$ {
            proxy_set_header X-Original-URL "$scheme://$host$request_uri";
            proxy_set_header X-Base-URL "$scheme://$host";
            proxy_pass http://cleezy-nginx.sce;
        }

        location ~ /recipe/(.*)$ {
            proxy_set_header X-Original-URL "$scheme://$host$request_uri";
            proxy_set_header X-Base-URL "$scheme://$host";
            proxy_pass http://recipe-nginx.sce;
            rewrite ^/recipe(.*)$ $1 break;
        }

        location ~ ^/recipe {
            return 302 $scheme://$http_host/recipe/;
        }        
        location ~ ^/transit/ {
            resolver 127.0.0.11 valid=15s;

            proxy_set_header   Host $host;
            set $upstream http://sceta-nginx.sce;
            proxy_pass $upstream;

            rewrite ^/transit(.*)$ $1 break;
        }

        location ~ ^/transit$ {
            return 302 $scheme://$http_host/transit/;
        }

        location ~ ^/status/ {
            resolver 127.0.0.11 valid=15s;

            proxy_set_header   Host $host;
            proxy_pass http://172.17.0.1:17000$is_args$args;

            rewrite ^/status(.*)$ $1 break;

            proxy_cache status_cache;
            proxy_cache_key "$uri$is_args$args";
            proxy_cache_valid 200 302 30s;
            proxy_cache_valid 404 1m;
            proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;
            # REMOVE proxy_cache_bypass unless you intend to bypass on a specific condition
            # proxy_cache_bypass $http_pragma;
            proxy_cache_revalidate on;

            add_header X-Cache-Status $upstream_cache_status;
            add_header Cache-Control "public, max-age=30, stale-while-revalidate=30";
        }
        location ~ ^/status$ {
            return 302 $scheme://$http_host/status/$is_args$args;
        }

        location ~ ^/spartan-compass(/.*)? {
            proxy_set_header Host $http_host;
            proxy_pass http://compass-app:3000;
        }

        #Load balancer
        location /api {
            proxy_pass http://mainendpoints;
        }
        location / {
            proxy_pass http://webserver;
        }
    }
}

events { }
