# Old TravisCI YAML file. For reference only.

branches:
  only:
  - dev
  - joon/Travis

language: node_js
node_js:
  - "lts/*"
services:
  - docker

# Build in travis VM for testing
before_install:
  - echo "Building docker images"
  - docker build -t repo.treescale.com/devscesjsu/sce-core-backend-dev:staging -f ./docker/Dockerfile-serverjs .
  - docker build -t repo.treescale.com/devscesjsu/sce-core-frontend-dev:staging -f ./docker/Dockerfile-ScePage .
  - echo "$DOCKER_PASSWORD" | docker login repo.treescale.com -u "$DOCKER_USERNAME" --password-stdin

# No testing yet.

install: true

before_script:
  - echo "Skipping testing"

script:
  - echo "Skipping testing"


# Deploy, push to TreeScale for docker repo.
# Will change one for dev and one for each repo in the future
deploy:
  - provider: script
    script: bash deploy_to_treescale.sh
    skip_cleanup: true
    on:
      branch: joon/Travis
  - provider: script
    script: bash deploy_to_treescale.sh
    skip_cleanup: true
    on:
      branch: dev
