FROM mongo:latest

RUN mkdir -p /data/db1

#RUN mkdir -p  /usr/src/app

#COPY package.json /usr/src/app/package.json
#COPY public/ /usr/src/app/public

#WORKDIR /usr/src/app/public/home/home-react/

VOLUME /data/db1/:/data/db/

EXPOSE 27017

CMD mongod --auth


