version: '3'
services:
 mongodb:
  image: "mongo"
  volumes:
   - "./data/db:/data/db"
  ports:
   - "27017:27017"
  restart: on-failure
 sce:
  container_name: sce_page
  image: 'core-v4_sce:latest'
  build:
   context: .
   dockerfile: ./docker/Dockerfile-sce
  ports:
   - '3000-3005:3000'
  depends_on:
   - serverjs
  links:
   - serverjs
  command: 'npm start'
  restart: on-failure
 serverjs:
  image: 'core-v4_serverjs:latest'
  build:
   context: . 
   dockerfile: ./docker/Dockerfile-serverjs
  ports:
   - '8080-8085:8080'
  links:
   - mongodb
  depends_on:
   - mongodb
  restart: on-failure
