FROM node:lts-alpine

RUN mkdir -p  /usr/src/app

COPY package.json /usr/src/app/package.json
COPY public/ /usr/src/app/public

WORKDIR /usr/src/app/public/home/home-react/

EXPOSE 3000

RUN npm install

CMD npm start
