FROM node:20.10.0-alpine as builder

WORKDIR /frontend

COPY ./package.json /frontend/package.json
COPY ./package-lock.json /frontend/package-lock.json

ARG NODE_ENV

ARG REACT_APP_BASE_API_URL

# see https://stackoverflow.com/a/61215597
ENV DANGEROUSLY_DISABLE_HOST_CHECK true

RUN npm install

COPY public ./public

COPY src ./src

COPY tailwind.config.js ./tailwind.config.js

RUN npx tailwindcss build -i src/input.css -o public/output.css --minify

CMD ["npm", "start"]
