FROM node:lts-alpine

RUN mkdir -p /usr/src/app

COPY src /usr/src/app/
COPY public /usr/src/app/
COPY util /usr/src/app/
COPY package.json /usr/src/app/

WORKDIR /usr/src/app

RUN npm install
COPY . ./
RUN npm run build

EXPOSE 8079

CMD npm run deploy-production-frontend