FROM node:lts-alpine

WORKDIR /frontend

RUN mkdir /frontend/public
RUN mkdir /frontend/src

# Copy the depencies
COPY package.json /frontend

# Copy the static files
COPY public/ /frontend/public

# Copy React source 
COPY src/ /frontend/src

EXPOSE 3000

RUN npm install

CMD npm start 
