FROM node:20.10.0-alpine as builder

WORKDIR /frontend

COPY ./frontend/package.json /frontend/package.json
COPY ./frontend/package-lock.json /frontend/package-lock.json

ARG NODE_ENV

ARG VITE_BASE_API_URL

# see https://stackoverflow.com/a/61215597
ENV DANGEROUSLY_DISABLE_HOST_CHECK true

RUN npm install

COPY ./frontend/public ./public

COPY ./frontend/src ./src

COPY ./frontend/tailwind.config.js ./tailwind.config.js

RUN npx tailwindcss build -i src/input.css -o public/output.css --minify

CMD ["npm", "start"]
