FROM node:alpine

WORKDIR /app

COPY package.json ./

RUN npm install

RUN npm install -g nodemon

EXPOSE 8082

ARG GENERAL_API_URL

ARG NODE_ENV

ARG VERIFICATION_BASE_URL

ARG DATABASE_HOST

CMD ["npm", "run", "cloud_api"]
