FROM node:alpine

WORKDIR /app

COPY package.json ./

RUN npm install

RUN npm install -g nodemon

EXPOSE 8080

ARG DISCORD_REDIRECT_URI

ARG NODE_ENV

ARG DATABASE_HOST

CMD [ "npm", "run", "main_endpoints"]
