FROM node:14.10.0-alpine 
#gets the base linux image

WORKDIR /app
#all commands will run in this directory

ENV DATABASE_HOST sce-mongodb-dev
#database env variable

COPY ./package.json /app/
#copies all the dependenices into work directory (./app) (since you set the work dir before)

RUN npm install 

RUN npm install -g nodemon
#installs packages

COPY ./peripheral_api /app/peripheral_api
#copies this file to the desination

COPY ./util/ /app/util/

COPY ./config/config.json /app/config/config.json

EXPOSE 8081

ENV DOCKER true

CMD [ "npm", "run", "peripheral_api" ]
