#gets the base linux image
FROM node:14.10.0-alpine 

#all commands will run in this directory
WORKDIR /app

#database env variable
ENV DATABASE_HOST sce-mongodb-dev

#copies all the dependenices into work directory (./app) (since you set the work dir before)
COPY ./package.json /app/

RUN npm install

#installs packages
RUN npm install -g nodemon

#copies this file to the desination
COPY ./peripheral_api /app/peripheral_api

COPY ./util/ /app/util/

COPY ./config/config.json /app/config/config.json

EXPOSE 8081

CMD [ "npm", "run", "peripheral_api" ]
